package com.hzq.db.greendao.sysdao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.hzq.db.greendao.entity.CommentEntity;
import com.hzq.db.greendao.entity.ProductEntity;

import com.hzq.db.greendao.sysdao.CommentEntityDao;
import com.hzq.db.greendao.sysdao.ProductEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig commentEntityDaoConfig;
    private final DaoConfig productEntityDaoConfig;

    private final CommentEntityDao commentEntityDao;
    private final ProductEntityDao productEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        commentEntityDaoConfig = daoConfigMap.get(CommentEntityDao.class).clone();
        commentEntityDaoConfig.initIdentityScope(type);

        productEntityDaoConfig = daoConfigMap.get(ProductEntityDao.class).clone();
        productEntityDaoConfig.initIdentityScope(type);

        commentEntityDao = new CommentEntityDao(commentEntityDaoConfig, this);
        productEntityDao = new ProductEntityDao(productEntityDaoConfig, this);

        registerDao(CommentEntity.class, commentEntityDao);
        registerDao(ProductEntity.class, productEntityDao);
    }
    
    public void clear() {
        commentEntityDaoConfig.getIdentityScope().clear();
        productEntityDaoConfig.getIdentityScope().clear();
    }

    public CommentEntityDao getCommentEntityDao() {
        return commentEntityDao;
    }

    public ProductEntityDao getProductEntityDao() {
        return productEntityDao;
    }

}
